# Generated by Django 6.0.5 on 2026-05-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
