# Generated by Django 6.0.5 on 2026-05-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0007_emailverificationtoken_passwordresetotp_request_ip_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailverificationtoken',
            name='email_verif_user_id_d93aeb_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailverificationtoken',
            name='email_verif_expires_770728_idx',
        ),
        migrations.RemoveIndex(
            model_name='passwordresetotp',
            name='password_re_request_7aa062_idx',
        ),
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='request_ip',
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
